// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCagj_7o9t7AspBMJNszCu8PSBoV-r_8NM',
    appId: '1:947337860520:web:2cb64584559951f007b99d',
    messagingSenderId: '947337860520',
    projectId: 'dukaletu2-66d0b',
    authDomain: 'dukaletu2-66d0b.firebaseapp.com',
    databaseURL: 'https://dukaletu2-66d0b-default-rtdb.firebaseio.com',
    storageBucket: 'dukaletu2-66d0b.firebasestorage.app',
    measurementId: 'G-9FSFHP8RMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKYCRzQCzax5nyHmqdiiBUn-r1nACMp4',
    appId: '1:947337860520:android:42e9efdcd6ea4e5207b99d',
    messagingSenderId: '947337860520',
    projectId: 'dukaletu2-66d0b',
    databaseURL: 'https://dukaletu2-66d0b-default-rtdb.firebaseio.com',
    storageBucket: 'dukaletu2-66d0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLd2UAcSuk-T-cEEp7IIcPUKXR04JuD_8',
    appId: '1:947337860520:ios:b78bbac7e48648eb07b99d',
    messagingSenderId: '947337860520',
    projectId: 'dukaletu2-66d0b',
    databaseURL: 'https://dukaletu2-66d0b-default-rtdb.firebaseio.com',
    storageBucket: 'dukaletu2-66d0b.firebasestorage.app',
    androidClientId: '947337860520-5f6la5hsf6ko5m92jvhi0t1ae96htnce.apps.googleusercontent.com',
    iosClientId: '947337860520-hnrrktda86j6prdq3tob9ifdf00ss6ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLd2UAcSuk-T-cEEp7IIcPUKXR04JuD_8',
    appId: '1:947337860520:ios:09913a74f94c4e3907b99d',
    messagingSenderId: '947337860520',
    projectId: 'dukaletu2-66d0b',
    databaseURL: 'https://dukaletu2-66d0b-default-rtdb.firebaseio.com',
    storageBucket: 'dukaletu2-66d0b.firebasestorage.app',
    androidClientId: '947337860520-5f6la5hsf6ko5m92jvhi0t1ae96htnce.apps.googleusercontent.com',
    iosClientId: '947337860520-ed8nired0j1ev5u2jl0itgc4tuafmgjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCagj_7o9t7AspBMJNszCu8PSBoV-r_8NM',
    appId: '1:947337860520:web:bc66ac545ed1e05707b99d',
    messagingSenderId: '947337860520',
    projectId: 'dukaletu2-66d0b',
    authDomain: 'dukaletu2-66d0b.firebaseapp.com',
    databaseURL: 'https://dukaletu2-66d0b-default-rtdb.firebaseio.com',
    storageBucket: 'dukaletu2-66d0b.firebasestorage.app',
    measurementId: 'G-VGZZG6EXJ1',
  );

}